export const RESET_ITEMS = "RESET_ITEMS";

export const SAVE_ITEM_START = "SAVE_ITEM_START";
export const SAVE_ITEM_SUCCESS = "SAVE_ITEM_SUCCESS";
export const SAVE_ITEM_FAILED = "SAVE_ITEM_FAILED";

export const SHARE_ITEM_START = "SHARE_ITEM_START";
export const SHARE_ITEM_SUCCESS = "SHARE_ITEM_SUCCESS";
export const SHARE_ITEM_FAILED = "SHARE_ITEM_FAILED";

export const ADD_ITEM_START = "ADD_ITEM_START";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILED = "ADD_ITEM_FAILED";

export const REMOVE_ITEM_START = "REMOVE_ITEM_START";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_FAILED = "REMOVE_ITEM_FAILED";

export const EDIT_ITEM_START = "EDIT_ITEM_START";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAILED = "EDIT_ITEM_FAILED";

export const FETCH_LOGGED_USER_START="FETCH_LOGGED_USER_START";
export const FETCH_LOGGED_USER_SUCCESS="FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_FAIL="FETCH_LOGGED_USER_FAIL";

export const FETCH_LOGGED_USER_ITEMS_START="FETCH_LOGGED_USER_ITEMS_START";
export const FETCH_LOGGED_USER_ITEMS_SUCCESS="FETCH_LOGGED_USER_ITEMS_SUCCESS";
export const FETCH_LOGGED_USER_ITEMS_FAILED="FETCH_LOGGED_USER_ITEMS_FAILED";

export const FETCH_ALL_USERS_START="FETCH_ALL_USERS_START";
export const FETCH_ALL_USERS_SUCCESS="FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILED="FETCH_ALL_USERS_FAILED";

export const FETCH_ITEMS_START="FETCH_ITEMS_START";
export const FETCH_ITEMS_SUCCESS="FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILED="FETCH_ITEMS_FAILED";

export const FETCH_ITEM_START="FETCH_ITEM_START";
export const FETCH_ITEM_SUCCESS="FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILED="FETCH_ITEM_FAILED";

export const LIKE_ITEM_SUCCESS = "LIKE_ITEM_SUCCESS";
export const LIKE_ITEM_FAILED = "LIKE_ITEM_FAILED";

export const UNLIKE_ITEM_SUCCESS = "UNLIKE_ITEM_SUCCESS";
export const UNLIKE_ITEM_FAILED = "UNLIKE_ITEM_FAILED";

export const AUTH_START = "AUTH_START"; 
export const AUTH_SUCCESS = "AUTH_SUCCESS"; 
export const AUTH_FAIL = "AUTH_FAIL"; 
export const AUTH_LOGOUT = "AUTH_LOGOUT"; 

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"; 

export const REMOVE_ALERT = "REMOVE_ALERT"; 
export const SET_ALERT = "SET_ALERT"; 

